### ISSUE TITLE
`64DistrictsBD`: Recounting already answered districts

### ISSUE THREAD

**Issue by aprotyas** [usiam/PersonalProjects#2]
See below, my input `Barisal` is being counted multiple times.

https://user-images.githubusercontent.com/34530011/122824295-77bdc500-d2ae-11eb-9e08-9b0a4d725e32.mp4

I believe the error is in this line https://github.com/usiam/PersonalProjects/blob/ed57f6e0026112015210991e114af85f2a38b2be/9.%2064DistrictsBD/main.py#L37

It can probably be fixed by changing the `if` block condition to:
```python
if answerDistrict in data.District.to_list() and answerDistrict not in guessedDistricts:
```

**Comment by usiam** [comment]
Fixed
